### ISSUE TITLE
just wondering if there is a way to change the prefix

### ISSUE THREAD

**Issue by devbubblegum** [rzmk/discord-palm-bot#3]
changing the prefix to @{insert bots discord username here} would be helpful.

**Comment by rzmk** [comment]
Hey @devbubblegum, I updated the bot. Feel free to check out the changes on the [README](https://github.com/rzmk/discord-palm-bot).

By default, mentioning the bot anywhere in the prompt should cause it to respond now (e.g., `@bot hey!`, `what's up @bot?`. You can disable this behavior with running the slash command `/respond_to_mention_in_prompt False`.

You may also set the prefix with `/prefix <prefix>` (e.g., `/prefix @bot`, `/prefix !`).

These values should be saved in `config.json` and whenever restarting the bot, whatever is in `config.json` would be the default values until you use the slash commands again or change the `config.json` values.

**Comment by devbubblegum** [comment]
alright thanks dude, this should help out with my project a lot, i will make sure to give you credit in it
